project:
  render: 
    - "*.qmd"
    - "!*_pub.qmd"
    - "!2022_soln.qmd"
  title: "seng404"
execute:
    freeze: auto  # re-render only when source changes
    echo: true     # show code
    eval: true     # run code
    results: show  # show output
output-dir:  _output
author:
  - name: Neil Ernst
    orcid: 0000-0001-5992-2366 
    email: nernst@uvic.ca
    affiliations: University of Victoria
format: 
  revealjs:
    theme: default
    slide-number: true
    code-fold: true  # optionally allow folding
    # highlight-style: obsidian
    logo: modules/images/ENGN_vert_bk.jpg
    footer: "Neil Ernst ©️ 2024-5"
    css: custom.css
date: last-modified

