project:
  render: 
    - "*.qmd"
    - "!2022_soln.qmd"
  title: "seng404"
output-dir:  _output
author:
  - name: Neil Ernst
    orcid: 0000-0001-5992-2366 
    email: nernst@uvic.ca
    affiliations: University of Victoria
format: 
  revealjs:
    theme: default
    slide-number: true
    logo: modules/images/ENGN_vert_bk.jpg
    footer: "Neil Ernst (c)"
date: last-modified



